import 'fake-indexeddb/auto'
import { beforeEach, expect, it, vi } from 'vitest'
import { db } from '@/db/schema'
import { frequencyDB, readFrequencyProgress } from './ieltsFrequencyProgress'
import { createInitialFSRSState } from './fsrsScheduler'
import type { NotebookItem } from '@/types'

const modules = import.meta.glob('./wordPractice.ts')
async function api() {
  expect(modules['./wordPractice.ts'], 'unified word practice core must exist').toBeDefined()
  return await modules['./wordPractice.ts']() as typeof import('./wordPractice')
}
const word = { id: 'one', word: 'station', answers: ['station'], meaning: '车站', source: 'frequency' as const, audio: '/real.mp3', sourceLabel: '高频原音' }
beforeEach(async () => { await db.delete(); await db.open(); await frequencyDB.delete(); await frequencyDB.open() })
it('keeps first failure across retry and excludes unanswered words from final statistics', async () => {
  const p = await api()
  let s = p.createPracticeSession('alice', 'ctx', [{ ...word, reason: 'spelling' as const }, { ...word, id: 'two' }])
  s = p.practiceReducer(s, { type: 'input', value: 'wrong' })
  s = p.practiceReducer(s, { type: 'check' })
  expect(s.firstVerdict).toBe(false)
  s = p.practiceReducer(s, { type: 'retry' })
  s = p.practiceReducer(s, { type: 'input', value: 'station' })
  s = p.practiceReducer(s, { type: 'check' })
  expect(s.firstVerdict).toBe(false)
  expect(s.verdict).toBe(true)
  s = await p.confirmPractice(s)
  s = p.practiceReducer(s, { type: 'finish' })
  expect(p.practiceSummary(s)).toMatchObject({ answered: 1, firstCorrect: 0, finalCorrect: 1 })
  expect(await readFrequencyProgress('alice')).toMatchObject([{ passed: false, attempts: 1, reason: 'spelling' }])
})
it('persists fixed queue and drafts by owner/context without duplicates on repeated confirm', async () => {
  const p = await api()
  let s = p.createPracticeSession('alice', 'ctx', [word])
  s = p.practiceReducer(s, { type: 'input', value: 'station' })
  await p.savePracticeSession(s)
  expect(await p.readPracticeSession('alice', 'ctx')).toMatchObject({ draft: 'station', queue: [word] })
  expect(await p.readPracticeSession('bob', 'ctx')).toBeNull()
  s = p.practiceReducer(s, { type: 'check' })
  await Promise.all([p.confirmPractice(s), p.confirmPractice(s)])
  expect(await readFrequencyProgress('alice')).toMatchObject([{ attempts: 1 }])
  expect((await p.readPracticeSettings('alice')).completed).toBe(1)
})
it('meaning practice never changes frequency dictation mastery', async () => {
  const p = await api()
  let s = p.createPracticeSession('alice', 'ctx', [word], 'meaning')
  s = p.practiceReducer(s, { type: 'input', value: 'station' })
  s = p.practiceReducer(s, { type: 'check' })
  await p.confirmPractice(s)
  expect(await readFrequencyProgress('alice')).toEqual([])
  expect((await p.readPracticeSettings('alice')).completed).toBe(0)
})
it('grades only notebook FSRS once and rolls back atomically on receipt failure', async () => {
  const p = await api()
  const fsrs = createInitialFSRSState()
  await db.notebook.put({ notebookId: 'one', type: 'vocabulary', content: 'station', exampleSentence: '', sourceCardId: 'sentence', sourceTag: 'CET4', fsrsNotebook: fsrs, createdAt: 1 })
  let s = p.createPracticeSession('alice', 'ctx', [{ ...word, source: 'notebook', notebookId: 'one' }])
  s = p.practiceReducer(s, { type: 'input', value: 'station' })
  s = p.practiceReducer(s, { type: 'check' })
  const failure = vi.spyOn(db.settings, 'put').mockRejectedValueOnce(new Error('quota'))
  await expect(p.confirmPractice(s)).rejects.toThrow('quota')
  failure.mockRestore()
  expect((await db.notebook.get('one'))?.fsrsNotebook.reps).toBe(0)
  await p.confirmPractice(s); await p.confirmPractice(s)
  expect((await db.notebook.get('one'))?.fsrsNotebook.reps).toBe(1)
  expect(await db.cards.count()).toBe(0)
})
it('blocks stale owner confirmation and only advances a saved correct result', async () => {
  const p = await api()
  let s = p.createPracticeSession('alice', 'ctx', [word])
  expect(await p.confirmPractice(s)).toBe(s)
  s = p.practiceReducer(s, { type: 'input', value: 'station' })
  s = p.practiceReducer(s, { type: 'check' })
  await expect(p.confirmPractice(s, () => false)).rejects.toThrow('会话')
  expect(await readFrequencyProgress('alice')).toEqual([])
})
it('recommends real wrong/due scope and parses level and bounded URL inputs', async () => {
  const p = await api()
  expect(p.parsePracticeOptions(new URLSearchParams('source=notebook&level=CET6&queue=due&limit=10&targetId=x'))).toMatchObject({ source: 'notebook', level: 'CET6', queue: 'due', limit: 10, targetId: 'x' })
  const words = [{ ...word, due: 100 }, { ...word, id: 'two', due: 300 }]
  expect(p.selectPracticeQueue(words, 'due', 200).map(w => w.id)).toEqual(['one'])
  expect(p.selectPracticeQueue(words.map(w => ({ ...w, wrong: w.id === 'two' })), 'mistakes', 200).map(w => w.id)).toEqual(['two'])
})
it('retains notebook sync work on failure and verifies authenticated owner before uploading', async () => {
  const p = await api()
  const item = { notebookId: 'one', type: 'vocabulary' as const, content: 'station', exampleSentence: '', sourceCardId: 'sentence', sourceTag: 'CET4', fsrsNotebook: createInitialFSRSState(), createdAt: 1 }
  await db.notebook.put(item)
  let s = p.createPracticeSession('alice', 'ctx', [{ ...word, source: 'notebook', notebookId: 'one' }])
  s = p.practiceReducer(s, { type: 'input', value: 'station' }); s = p.practiceReducer(s, { type: 'check' })
  await p.confirmPractice(s)
  const upload = vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValue(undefined)
  expect(p.processPracticeNotebookSync).toBeDefined()
  await p.processPracticeNotebookSync('alice', async () => 'bob', upload)
  expect(upload).not.toHaveBeenCalled()
  await expect(p.processPracticeNotebookSync('alice', async () => 'alice', upload)).rejects.toThrow('offline')
  await p.processPracticeNotebookSync('alice', async () => 'alice', upload)
  expect(upload).toHaveBeenCalledTimes(2)
  expect(upload.mock.calls[1][1].fsrsNotebook.reps).toBe(1)
  await p.processPracticeNotebookSync('alice', async () => 'alice', upload)
  expect(upload).toHaveBeenCalledTimes(2)
})
it('enriches only exact dictionary matches and preserves supplied real meaning', async () => {
  const p = await api()
  expect(p.enrichPracticeWords).toBeDefined()
  const words = [{ ...word, meaning: '' }, { ...word, id: 'other', word: 'station master', meaning: '' }, { ...word, id: 'known' }]
  const enriched = p.enrichPracticeWords(words, { source: 'ECDICT', words: { station: { meaning: 'n. 车站', ipa: 'steɪʃən', partOfSpeech: 'n.' } } })
  expect(enriched[0]).toMatchObject({ meaning: 'n. 车站', ipa: 'steɪʃən', metadataSource: 'ECDICT' })
  expect(enriched[1].meaning).toBe('')
  expect(enriched[2].meaning).toBe('车站')
})
it('returns to the exact IELTS source selection or notebook vocabulary tab', async () => {
  const p = await api()
  expect(p.practiceSourceUrl).toBeDefined()
  expect(p.practiceSourceUrl(p.parsePracticeOptions(new URLSearchParams('source=frequency&chapter=2&section=B&limit=10')))).toBe('/ielts/listening?source=frequency&chapter=2&section=B&limit=10')
  expect(p.practiceSourceUrl(p.parsePracticeOptions(new URLSearchParams('source=notebook&level=CET6')))).toBe('/notebook?tab=vocabulary')
})
it('atomically rolls frequency grade back when its canonical confirmation/session storage fails', async () => {
  const p = await api()
  expect(frequencyDB.practiceState, 'frequency confirmation needs canonical same-database session storage').toBeDefined()
  let s = p.createPracticeSession('alice', 'ctx', [word])
  s = p.practiceReducer(s, { type: 'input', value: 'station' }); s = p.practiceReducer(s, { type: 'check' })
  await p.savePracticeSession(s)
  const failure = vi.spyOn(frequencyDB.practiceState, 'put').mockRejectedValueOnce(new Error('quota'))
  await expect(p.confirmPractice(s)).rejects.toThrow('quota')
  failure.mockRestore()
  expect(await readFrequencyProgress('alice')).toEqual([])
  expect(await frequencyDB.receipts.count()).toBe(0)
  expect(await p.readPracticeSession('alice', 'ctx')).toMatchObject({ position: 0, draft: 'station', verdict: true })
  await p.confirmPractice(s)
  expect(await readFrequencyProgress('alice')).toMatchObject([{ attempts: 1, passed: true }])
})
it('recovers committed frequency queue after secondary display/settings reads fail and derives mixed-source daily totals', async () => {
  const p = await api()
  let s = p.createPracticeSession('alice', 'ctx', [word, { ...word, id: 'two' }])
  s = p.practiceReducer(s, { type: 'input', value: 'station' }); s = p.practiceReducer(s, { type: 'check' })
  await p.confirmPractice(s)
  const failure = vi.spyOn(db.settings, 'get').mockRejectedValueOnce(new Error('secondary'))
  await expect(p.readPracticeSettings('alice')).rejects.toThrow('secondary')
  failure.mockRestore()
  frequencyDB.close(); await frequencyDB.open()
  expect(await p.readPracticeSession('alice', 'ctx')).toMatchObject({ position: 1, results: [{ id: 'one' }] })
  let other = p.createPracticeSession('alice', 'wanglu', [{ ...word, source: 'wanglu' }])
  other = p.practiceReducer(other, { type: 'input', value: 'station' }); other = p.practiceReducer(other, { type: 'check' })
  await p.confirmPractice(other)
  const prefs = await p.readPracticeSettings('alice')
  expect(prefs.completed).toBe(2)
  await p.savePracticeSettings('alice', { ...prefs, completed: 1000, dailyTarget: 7 })
  expect(await p.readPracticeSettings('alice')).toMatchObject({ completed: 2, dailyTarget: 7 })
  await db.settings.put({ key: 'word-practice:settings:alice', value: { ...prefs, completed: 9999 } })
  expect((await p.readPracticeSettings('alice')).completed).toBe(2)
})
it('clears a notebook pending mistake after a later first-correct round despite retained lifetime FSRS lapses', async () => {
  const p = await api()
  await db.notebook.put({ notebookId: 'one', type: 'vocabulary', content: 'station', exampleSentence: '', sourceCardId: 'sentence', sourceTag: 'CET4', fsrsNotebook: { ...createInitialFSRSState(), lapses: 3 }, createdAt: 1 })
  let s = p.createPracticeSession('alice', 'ctx', [{ ...word, source: 'notebook', notebookId: 'one' }])
  s = p.practiceReducer(s, { type: 'input', value: 'wrong' }); s = p.practiceReducer(s, { type: 'check' })
  s = p.practiceReducer(s, { type: 'retry' }); s = p.practiceReducer(s, { type: 'input', value: 'station' }); s = p.practiceReducer(s, { type: 'check' })
  await p.confirmPractice(s)
  const options = p.parsePracticeOptions(new URLSearchParams('source=notebook&queue=mistakes'))
  expect(p.selectPracticeQueue(await p.loadPracticeWords('alice', options), 'mistakes').map(w => w.id)).toEqual(['one'])
  let independent = p.createPracticeSession('alice', 'new', [{ ...word, source: 'notebook', notebookId: 'one' }])
  independent = p.practiceReducer(independent, { type: 'input', value: 'station' }); independent = p.practiceReducer(independent, { type: 'check' })
  await p.confirmPractice(independent)
  expect((await db.notebook.get('one'))!.fsrsNotebook.lapses).toBeGreaterThan(0)
  expect(p.selectPracticeQueue(await p.loadPracticeWords('alice', options), 'mistakes')).toEqual([])
})
it('derives today only after midnight and merges counters without replacing newer preferences', async () => {
  const p = await api()
  expect(p.readPracticeDailyProgress).toBeDefined()
  expect(p.mergePracticeDailyProgress).toBeDefined()
  vi.useFakeTimers({ toFake: ['Date'] })
  try {
    vi.setSystemTime(new Date(2026, 9, 9, 23, 59, 59))
    let yesterday = p.createPracticeSession('alice', 'yesterday', [word])
    yesterday = p.practiceReducer(yesterday, { type: 'input', value: 'station' }); yesterday = p.practiceReducer(yesterday, { type: 'check' })
    await p.confirmPractice(yesterday)
    const cached = { ...await p.readPracticeSettings('alice'), dailyTarget: 7, voice: 'latest-user-voice' }
    expect(cached.completed).toBe(1)
    vi.setSystemTime(new Date(2026, 9, 10, 0, 0, 1))
    let current = p.createPracticeSession('alice', 'today', [word])
    current = p.practiceReducer(current, { type: 'input', value: 'station' }); current = p.practiceReducer(current, { type: 'check' })
    await p.confirmPractice(current)
    const today = await p.readPracticeDailyProgress('alice')
    expect(today).toEqual({ date: '2026-10-10', completed: 1 })
    expect(p.mergePracticeDailyProgress(cached, today)).toMatchObject({ date: '2026-10-10', completed: 1, dailyTarget: 7, voice: 'latest-user-voice' })
  } finally { vi.useRealTimers() }
})
it('drops deleted notebook sync jobs without re-uploading their captured snapshot', async () => {
  const p = await api()
  await db.settings.put({ key: 'word-practice:sync:alice:one', value: { item: { notebookId: 'one', fsrsNotebook: createInitialFSRSState() }, token: 'old' } })
  const upload = vi.fn()
  await p.processPracticeNotebookSync('alice', async () => 'alice', upload)
  expect(upload).not.toHaveBeenCalled()
  expect(await db.settings.get('word-practice:sync:alice:one')).toBeUndefined()
})
it('uploads current notebook FSRS rather than a pending confirmation snapshot', async () => {
  const p = await api()
  const old = { notebookId: 'one', type: 'vocabulary' as const, content: 'station', exampleSentence: '', sourceCardId: 'sentence', sourceTag: 'CET4', fsrsNotebook: createInitialFSRSState(), createdAt: 1 }
  await db.settings.put({ key: 'word-practice:sync:alice:one', value: { item: old, token: 'old' } })
  const current = { ...old, fsrsNotebook: { ...old.fsrsNotebook, reps: 7 } }
  await db.notebook.put(current)
  const upload = vi.fn()
  await p.processPracticeNotebookSync('alice', async () => 'alice', upload)
  expect(upload).toHaveBeenCalledWith('alice', current)
})
it('corrects a deletion or newer local review occurring while the cloud upload is pending', async () => {
  const p = await api()
  const item = { notebookId: 'one', type: 'vocabulary' as const, content: 'station', exampleSentence: '', sourceCardId: 'sentence', sourceTag: 'CET4', fsrsNotebook: createInitialFSRSState(), createdAt: 1 }
  await db.notebook.put(item)
  await db.settings.put({ key: 'word-practice:sync:alice:one', value: { item, token: 'old' } })
  const remove = vi.fn()
  await p.processPracticeNotebookSync('alice', async () => 'alice', async () => { await db.notebook.delete('one') }, remove)
  expect(remove).toHaveBeenCalledWith('alice', 'one')
  await db.notebook.put(item)
  await db.settings.put({ key: 'word-practice:sync:alice:one', value: { item, token: 'second' } })
  const upload = vi.fn(async (owner: string, sent: NotebookItem) => { expect(owner).toBe('alice'); expect(sent.notebookId).toBe('one'); if (upload.mock.calls.length === 1) await db.notebook.update('one', { fsrsNotebook: { ...item.fsrsNotebook, reps: 9 } }) })
  await p.processPracticeNotebookSync('alice', async () => 'alice', upload, remove)
  expect(upload).toHaveBeenCalledTimes(2)
  expect(upload.mock.calls[1][1].fsrsNotebook.reps).toBe(9)
  expect(await db.settings.get('word-practice:sync:alice:one')).toBeUndefined()
})
it('retries failed preferences before a practice session has been started', async () => {
  const p = await api()
  expect(p.retryPracticeSave).toBeDefined()
  const settings = { ...p.defaultPracticeSettings, speed: 1.25, dailyTarget: 7 }
  const failure = vi.spyOn(db.settings, 'put').mockRejectedValueOnce(new Error('quota'))
  await expect(p.retryPracticeSave('alice', null, settings)).rejects.toThrow('quota')
  failure.mockRestore()
  await p.retryPracticeSave('alice', null, settings)
  expect(await p.readPracticeSettings('alice')).toMatchObject({ speed: 1.25, dailyTarget: 7, completed: 0 })
  expect(await p.readPracticeSession('alice', 'none')).toBeNull()
})
