server {
    listen 80;
    listen [::]:80;
    server_name listening.website www.listening.website;
    root /var/www/cet-listening;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
